logging:
  level:
    root: warn
    teamc.opgg.swoomi: debug #debug info warn error fatal off

server:
  port: 8070

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: create
      format_sql: true
    showSql: true
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftlh
  config:
    activate:
      on-profile: local

#local_private.yml, real_private.yml 형태
#riot:
#  api:
#    key:
#spring:
#  datasource:
#    password: