spring:
  profiles:
    include:

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftlh