logging:
  level:
    root: warn
    teamc.opgg.swoomi: debug
  file:
    path: /home/ubuntu/app/log

  logback:
    rollingpolicy:
      max-history: 7

server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:database-web-c.cxadkdwc8e90.ap-northeast-2.rds.amazonaws.com}:3306/swoomi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      ddl-auto: update
      format_sql: true
    generate-ddl: false
    show-sql: true
    open-in-view: false
  config:
    activate:
      on-profile: real