logging:
  level:
    root: warn
    teamc.opgg.swoomi: debug #debug info warn error fatal off

server:
  port: 8070

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: create
      format_sql: true
    showSql: true
    open-in-view: false
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  sql:
    init:
      mode: never