spring:
  profiles:
#    include: real,real_private
    include: local,local_private
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftlh
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    teamc:
      opgg:
        swoomi:
          config:
            SwoomiRequestLoggingFilter: DEBUG
